-- ====================================================================
-- QUANTFLOW TRADING SYSTEM - SUPABASE DATABASE SCHEMA
-- Copy and paste this script into your Supabase SQL Editor and click "RUN"
-- Project: https://wutdxnmvrvzogkotyjoz.supabase.co
-- ====================================================================

-- 1. Orders & Trade Executions Table
CREATE TABLE IF NOT EXISTS public.orders (
    order_id TEXT PRIMARY KEY,
    client_order_id TEXT,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    fill_price NUMERIC(12, 4),
    status TEXT NOT NULL DEFAULT 'SUBMITTED',
    order_type TEXT NOT NULL DEFAULT 'MARKET',
    type TEXT DEFAULT 'REGULAR',
    source TEXT DEFAULT 'SYSTEM',
    reasoning TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Multi-Agent Signal Logs Table
CREATE TABLE IF NOT EXISTS public.signal_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    direction TEXT NOT NULL,
    confidence NUMERIC(5, 4) NOT NULL,
    reasoning TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Deterministic Risk Gate Audit Logs Table
CREATE TABLE IF NOT EXISTS public.risk_decision_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    approved BOOLEAN NOT NULL,
    allowed_quantity INTEGER NOT NULL,
    violations JSONB DEFAULT '[]'::jsonb,
    reasons JSONB DEFAULT '[]'::jsonb,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signal_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_decision_logs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they already exist to ensure idempotency
DROP POLICY IF EXISTS "Allow public read/insert orders" ON public.orders;
DROP POLICY IF EXISTS "Allow public read/insert signal_logs" ON public.signal_logs;
DROP POLICY IF EXISTS "Allow public read/insert risk_decision_logs" ON public.risk_decision_logs;

-- Recreate policies allowing Anon & Service Role keys full access
CREATE POLICY "Allow public read/insert orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/insert signal_logs" ON public.signal_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read/insert risk_decision_logs" ON public.risk_decision_logs FOR ALL USING (true) WITH CHECK (true);

-- Success message
SELECT 'QUANTFLOW Database Schema successfully initialized!' AS status;
